### ISSUE TITLE
Needs update to be compatible with SAMD boards

### ISSUE THREAD

**Issue by tigoe** [arduino-libraries/TFT#21]
Line 1 of glcffont.c needs this added: 
````
&& !defined(ARDUINO_ARCH_SAMD)
````
Also, it looks like the Adafruit libraries in /utilities are out of date with the current version. Current Adafruit_GFX appears to have a very different API, no longer features background() and many of the other Processing-style functions.

**Comment by aentinger** [comment]
Fixed by #27.
