### ISSUE TITLE
Merge Fix for TFT Library to stable Release branch ?

### ISSUE THREAD

**Issue by agdl** [arduino-libraries/TFT#5]
_From @ankitdaf on December 11, 2014 11:13_

https://github.com/arduino/Arduino/commit/cb7b62f43eb1723f59ebfda5bbafa29d7a22771b <-
This was fixed in beta branch, but not in stable. I think it's high time we merge it into the release branch

_Copied from original issue: arduino/Arduino#2493_

**Comment by per1234** [comment]
Closing as fixed because the commit is now in release versions of the TFT library which are bundled with the Arduino IDE releases.
