### ISSUE TITLE
TFT library not working with Arduino 1.0.5 

### ISSUE THREAD

**Issue by agdl** [arduino-libraries/TFT#7]
_From @Filip- on June 4, 2014 7:30_

I use the Arduino TFT LCD Screen. From its reference page  I got to the TFT library reference page [1] where it is  written :

Quote: ".. The TFT library is included with Arduino IDE 1.0.5 and later.... "

 but for me it is only working with Arduino 1.5.5 BETA downloaded from 2. 
( I only tested 1.0.5 and then 1.5.5 BETA on Uno and Mega ) 

I think that the quoted statement above is confusing, since you get the impression that the library in 1.0.5 is also working for the Arduino TFT LCD Screen .

[1] http://arduino.cc/en/Reference/TFTLibrary
[2] http://arduino.cc/en/Main/OldSoftwareReleases

_Copied from original issue: arduino/Arduino#2108_

**Comment by per1234** [comment]
Closing because Arduino IDE 1.0.5 is no longer supported. In theory, the version of the library bundled with Arduino IDE 1.0.5 should work fine with Arduino IDE 1.0.5, but if not the user should just update their IDE version.
